### ISSUE TITLE
The download link of the pre-trained model is invalid

### ISSUE THREAD

**Issue by JWargrave** [SCLBD/MCG-Blackbox#1]
https://drive.google.com/drive/folders/1--9p_jdAFnlo49_ZYfuGxxShChemqi_F?usp=sharing

The link of pre-trained models is invalid

**Comment by FeiiYin** [comment]
Hi, thanks for your attention. I have updated the checkpoint with the following link:
https://drive.google.com/drive/folders/18m4KY-J3kpAcXGgmMmGroFz08DGxA2FU?usp=sharing
