### ISSUE TITLE
How exactly is this achieved

### ISSUE THREAD

**Issue by tanlingp** [SCLBD/MCG-Blackbox#3]
Hi, I'm very interested in your -this- paper. But I don't seem to understand how you used Bayesian methods to train the model and how exactly you implemented it? Please also enlighten me

**Comment by FeiiYin** [comment]
Hi, Thanks for your interest in our work! About the bayesian methods, e.g. cg-attack, map the adversarial distribution to a dense low-dimension distribution or a simple gaussian distribution via a generator (c-Glow for cg-attack and ours). 
During the training, like adv-gan, we can directly use the generated adversarial examples to attack the surrogate or target model and employ the adversarial loss to update the generator parameters.
During the inference, we can sample a latent from the gaussian distribution to generate an adversarial example from the trained generator. We can further improve the ability of the attacking by tuning the latent, generator parameters, and the adversarial example itself with different off-the-shelf black-box-attack methods.
We incorporate a meta-learning updating strategy when updating the generator parameters.

However, the drawback of such methods is requiring our model to fit the specific domain of data, which takes a long time to train. Although meta-learning can help us improve the instance-level transfer-ability, and achieve a relatively good performance in new datasets. It is currently being surpassed by some data-free transfer methods, like [this](Boosting the Transferability of Adversarial Attacks with Reverse Adversarial Perturbation).
