### ISSUE TITLE
关于找不到train_imagenet.py文件问题

### ISSUE THREAD

**Issue by StarrySky123123123** [SCLBD/MCG-Blackbox#4]
您好，我根据README.md说明，执行imagenet_metatrain.sh文件，里面有需要一个文件为train_imagenet.py来进行元训练，这一步在预训练 c-Glow 以提供对扰动分布建模的初始状态后进行。但是我在项目中没有找到train_imagenet.py这个文件。

还盼回复

**Comment by FeiiYin** [comment]
Sorry, we merge the train_imagenet.py and train_cifar.py into the train.py, you can specify the parameters "dataset_name" to train on imagenet dataset.
